hostname: DC-B-CORE
loopback_ip: 10.255.0.2
as_number: 65002

lan_interfaces:
  - name: GigabitEthernet0/0
    description: "DC-B internal services (analytics-db = 10.2.2.10)"
    ip: 10.2.2.1
    netmask: 255.255.255.0
    network: 10.2.2.0

wan_interfaces:
  - name: GigabitEthernet0/1
    description: "WAN to BRANCH-01"
    ip: 172.16.11.1
    netmask: 255.255.255.252
    neighbor_ip: 172.16.11.2
    neighbor_as: 65101
    neighbor_description: "eBGP to BRANCH-01"
  - name: GigabitEthernet0/2
    description: "WAN to BRANCH-02"
    ip: 172.16.12.1
    netmask: 255.255.255.252
    neighbor_ip: 172.16.12.2
    neighbor_as: 65102
    neighbor_description: "eBGP to BRANCH-02"
  - name: GigabitEthernet0/3
    description: "WAN to BRANCH-03"
    ip: 172.16.13.1
    netmask: 255.255.255.252
    neighbor_ip: 172.16.13.2
    neighbor_as: 65103
    neighbor_description: "eBGP to BRANCH-03"

acls: []
